### ISSUE TITLE
Flesh out a short piece on the problem we are solving

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#70]
@ButtercupUltra 
I think we need to shift our frame of reference to that of a product. So we should come up with a snappy consolidation of what problem we are trying to solve with the app. This will help with marketing, showcasing our app, slide deck and for any business negotiations or meetings we may have. Including some stats may be useful, how many people require cataracts... how many companies provide IOL, what are the error rates with choosing the wrong IOL, what are the clinical consequences of choosing the wrong IOL. 

You mentioned they did some research on the failure rate of IOLs locally, any chance we could have a look at that ?

**Questions to think about** 

1. Who are the users for your product? (Relatively straight forward)
2. Are you really fulfilling their needs? (Can talk about this when you and your colleagues do some alpha testing) 
3. Is your app scalable ? (Answer is probably yes, but we just need to think about it)
4. What are your app’s priorities? (To just solidify what we want it to do in writing, I suspect you have a good idea on this)

We may want to create a shared Google Drive where we can work on documents together, or something similar for internal documents.

**Comment by ButtercupUltra** [comment]
Cataract surgery is the single most common surgical procedure performed in the world today. 
Cataract is the largest contributor to blindness in adults aged 50 years and older in 2020.  More than 15 million individuals, approximately 45% of the 33·6 million cases of global blindness, needed cataract surgery as of last year, according to the Vision Loss Expert Group of the Global Burden of Disease Study (_Lancet Glob Health 2021; 9: e144–60_). For each eye that will have a cataract removed, an artificial intraocular lens (IOL) needs to be implanted.  Each IOL is specific to the eye it will be placed in and needs to be calculated accordingly. 

The impact of cataract surgery in a person’s life is undeniable, and new advances have made the procedure less invasive while achieving excellent results.  Although the technology has developed substantially, there are still mishaps when calculating the intra-ocular lens needed for each patient. Lens calculation has become more straight-forward with programming suites provided in biometry machines.  However, there can be situations when a proposed lens needs to be changed suddenly, greatly increasing the chances of a refractive surprise.  Likewise, some surgeons have a wide range of lenses at their disposal, and the varying constants and aspects of different lenses can be confusing and lead to errors in calculation.

As an ophthalmologist working in Mexico and the UK for the past five years, I’ve witnessed and experienced these scenarios first-hand.  Although there are a number of websites with optimised constants at our disposal (such as ULIB and IOLCon), it is tedious having to go through the long lists of lenses provided.  This is impossible to do in theatre, if there has been any mishap with the lenses and a quick calculation is needed.  Similarly, I’ve witnessed fellow doctors choosing sub-optimal lenses for the sake of streamlining their practice and their surgical lists.  With all the technological advances provided by lens manufacturers, it is a shame they can’t be fully taken advantage due to operational constraints in the field.

IOL Assist is being developed as a solution to these scenarios. It will provide a powerful tool to access the data listed at ULIB and IOL Con in a user-friendly, no-thrills fashion. The intention is for surgeons to have all the data needed for accurate calculations at their fingertips.  IOL Assist is not intended as a calculator, but may provide the data needed as input for other online calculators. 
It will be an invaluable tool for determining the best alternatives for IOL selection, as well as readily accessing data specific to each lens in the market. Eye care professionals can also benefit from other useful functions, such as quick reference for sulcus implantation, determining best size of capsular tension rings, and verifying the material of a particular IOL.

IOL Assist provides direct links to the official lens websites for a more in-depth read, as well as links to the most up-to-date constant databases.

Key Points

1. End user:  
The goal of the app is to aid everyone and anyone involved in the IOL selection.  It is clearly aimed with surgeons as the main target, providing constants, material, diopter range, and other key aspects of  IOLs in a clear, consistent manner.  There is a strong argument in using the app with learning purposes (adding an IOL Wiki function) for trainees, which could aid with the scalability of the app and widen its target audience. 

2. Needs fulfilled: 
There is a clear need for this app.  Although not as tangible in the NHS, as a specific Trust will normally handle just a few IOLs, the need is there for doctors in practices with a wider range of IOLs. This is the case for the USA, Latin America, India, among others. The main need fulfilled > there is currently no tool to quickly, consistently, and accurately display key data of a wide range of lenses in a mobile device

3. Scalability: 
There is real potential to scale the use of the app internationally.  Main target is the USA and Latin America, as the health model for ophthalmology revolves around private practice.  The availability and diversity of lenses is huge and this app could easily be readily adopted.

4. Priorities: 
Provide optimised constants, sizes, design, and other aspects of IOLs

**Comment by medic-code** [comment]
This is excellent Juan really hitting the nail on the head. 

"Each IOL is specific to the eye it will be placed in and needs to be calculated accordingly." --> Why ? (I realise this is a stupid question but what are the consequences of a sub-optimal fitted IOL ? ) could you expand on that abit ? - Data is good to have at your fingertips when trying to convince others.

"The impact of cataract surgery in a person’s life is undeniable," - I agree, do we have any data on what that impact is ? Similar reason - data helps convince those that would say so what ?

**Other comments on some of the things you mention**

As a side - IOL wiki function this seems like an interesting idea and worth thinking about about as a side aspect. 

Interesting you mention the need is greatest in the USA and Latin America - I think from a financial perspective this also works out better - Whilst the NHS has lots of money - as you say the key part is too much choice - NHS doesn't suffer from that.



From the above text you've provided I think we can incorporate this into an email to IOL Con in a seperate issue - Will have a look at this and the other issue to modify it.

**Comment by medic-code** [comment]
I've copied this into monday.com now so will close.
